export const dummy = [
    {
        id: '15CH2217',
        contractor: 'EARTHPURE',
        contractName: 'Sit amet esse id labore incididunt consectetur ad adipisicing ullamco.',
        description: 'Pariatur labore dolor ex pariatur. Eiusmod qui mollit culpa in aliqua fugiat sunt ex.',
        effectivityDate: '08/26/2014',
        expiryDate: '06/29/2019',
        status: 'nys',
        accomplishment: 96,
        duration: 35
    },
    {
        id: '15CH2781',
        contractor: 'SQUISH',
        contractName: 'Velit dolor culpa nisi ipsum aliquip deserunt.',
        description: 'Cupidatat pariatur qui laboris exercitation excepteur do ipsum. Labore culpa laborum sit cillum eiusmod qui est sunt elit mollit.',
        effectivityDate: '03/13/2014',
        expiryDate: '11/19/2017',
        status: 'completed',
        accomplishment: 52,
        duration: 21
    },
    {
        id: '15CH8424',
        contractor: 'CENTREE',
        contractName: 'Ad nostrud proident quis laboris occaecat esse veniam in laborum sunt fugiat nostrud.',
        description: 'Sunt ullamco sint voluptate proident ex tempor excepteur consectetur aliqua. Laborum esse voluptate cillum dolor laborum labore dolore.',
        effectivityDate: '01/04/2014',
        expiryDate: '02/28/2017',
        status: 'ongoing',
        accomplishment: 59,
        duration: 22
    }
    // {
    //     'id': '15CH9469',
    //     'contractor': 'BUNGA',
    //     'contractName': 'Laborum consectetur elit ad pariatur esse voluptate commodo elit laboris fugiat commodo.',
    //     'description': 'Laborum sint enim anim do id sint aute exercitation deserunt dolore anim exercitation. Reprehenderit anim duis consequat anim mollit non reprehenderit aliqua.',
    //     'effectivityDate': '06/23/2015',
    //     'expiryDate': '02/22/2017',
    //     'status': 'terminated',
    //     'accomplishment': 12,
    //     'duration': 92
    // },
    // {
    //     'id': '15CH7588',
    //     'contractor': 'NETERIA',
    //     'contractName': 'Incididunt amet aute qui veniam tempor id adipisicing sint mollit sit ut sunt consequat.',
    //     'description': 'Consequat fugiat velit pariatur commodo nisi cupidatat occaecat ad exercitation exercitation. Nulla occaecat est culpa aute non officia.',
    //     'effectivityDate': '05/10/2014',
    //     'expiryDate': '01/19/2021',
    //     'status': 'ongoing',
    //     'accomplishment': 19,
    //     'duration': 56
    // },
    // {
    //     'id': '15CH3320',
    //     'contractor': 'BESTO',
    //     'contractName': 'Consequat ea proident exercitation aliqua cupidatat aliqua cupidatat nostrud culpa est quis.',
    //     'description': 'Laboris aute sunt ut sit excepteur velit mollit. Proident ut enim excepteur cillum consectetur occaecat consequat non labore voluptate commodo id.',
    //     'effectivityDate': '08/16/2014',
    //     'expiryDate': '10/27/2020',
    //     'status': 'nys',
    //     'accomplishment': 54,
    //     'duration': 42
    // },
    // {
    //     'id': '15CH9100',
    //     'contractor': 'ARTWORLDS',
    //     'contractName': 'Occaecat dolore dolor esse cillum.',
    //     'description': 'Sunt eu dolor id officia cupidatat incididunt ea. In amet labore pariatur qui pariatur eu sunt laborum nisi exercitation pariatur Lorem.',
    //     'effectivityDate': '05/20/2014',
    //     'expiryDate': '04/26/2017',
    //     'status': 'ongoing',
    //     'accomplishment': 54,
    //     'duration': 100
    // },
    // {
    //     'id': '15CH2905',
    //     'contractor': 'KENEGY',
    //     'contractName': 'Elit ea minim Lorem sit laboris.',
    //     'description': 'Sint fugiat laborum tempor velit. Elit in qui in amet non officia mollit voluptate exercitation.',
    //     'effectivityDate': '03/18/2014',
    //     'expiryDate': '12/27/2020',
    //     'status': 'nys',
    //     'accomplishment': 31,
    //     'duration': 32
    // },
    // {
    //     'id': '15CH6506',
    //     'contractor': 'HOMELUX',
    //     'contractName': 'Adipisicing sunt aliquip cupidatat officia qui ipsum nostrud.',
    //     'description': 'Labore qui aliqua ex sint proident. Fugiat ex ad non est culpa veniam.',
    //     'effectivityDate': '07/26/2014',
    //     'expiryDate': '11/21/2018',
    //     'status': 'nys',
    //     'accomplishment': 34,
    //     'duration': 90
    // },
    // {
    //     'id': '15CH1926',
    //     'contractor': 'SECURIA',
    //     'contractName': 'Occaecat culpa dolore labore nisi qui commodo eu ipsum cupidatat quis est do ea esse.',
    //     'description': 'Reprehenderit esse velit qui cillum amet officia. Nulla duis sunt labore consectetur id reprehenderit do nulla anim.',
    //     'effectivityDate': '03/12/2014',
    //     'expiryDate': '07/12/2019',
    //     'status': 'nys',
    //     'accomplishment': 42,
    //     'duration': 62
    // },
    // {
    //     'id': '15CH7627',
    //     'contractor': 'XEREX',
    //     'contractName': 'Ad sint sunt incididunt magna non ad aute amet commodo exercitation cillum ad exercitation.',
    //     'description': 'Culpa in culpa non veniam qui nisi. Commodo excepteur eu tempor anim mollit aliquip est officia nisi culpa et.',
    //     'effectivityDate': '11/08/2014',
    //     'expiryDate': '11/24/2020',
    //     'status': 'ongoing',
    //     'accomplishment': 11,
    //     'duration': 62
    // },
    // {
    //     'id': '15CH8638',
    //     'contractor': 'ORBALIX',
    //     'contractName': 'Et aute occaecat aliquip sunt excepteur elit nulla reprehenderit proident elit ad consectetur ad irure.',
    //     'description': 'Tempor esse proident minim cillum deserunt laborum enim in incididunt occaecat tempor ullamco consectetur. Eiusmod tempor proident velit eu id ipsum commodo.',
    //     'effectivityDate': '04/09/2015',
    //     'expiryDate': '03/06/2018',
    //     'status': 'accepted',
    //     'accomplishment': 22,
    //     'duration': 20
    // },
    // {
    //     'id': '15CH9879',
    //     'contractor': 'OPTICOM',
    //     'contractName': 'Ea aliquip do ad ut officia pariatur enim.',
    //     'description': 'Mollit deserunt amet cupidatat ullamco mollit mollit fugiat aliqua consequat nostrud consectetur in culpa reprehenderit. Amet sunt ea duis minim elit cillum nisi cillum ex.',
    //     'effectivityDate': '11/01/2014',
    //     'expiryDate': '11/22/2016',
    //     'status': 'accepted',
    //     'accomplishment': 19,
    //     'duration': 79
    // },
    // {
    //     'id': '15CH1961',
    //     'contractor': 'GEEKULAR',
    //     'contractName': 'Eu proident amet aliquip ipsum excepteur commodo id commodo do occaecat Lorem anim aliqua.',
    //     'description': 'Ea amet commodo voluptate eiusmod anim duis Lorem. Quis occaecat nostrud laborum Lorem amet elit quis est officia.',
    //     'effectivityDate': '04/30/2015',
    //     'expiryDate': '08/16/2020',
    //     'status': 'terminated',
    //     'accomplishment': 50,
    //     'duration': 80
    // },
    // {
    //     'id': '15CH7525',
    //     'contractor': 'SARASONIC',
    //     'contractName': 'Adipisicing id elit nulla labore qui aliqua eu aliqua laboris magna velit enim esse incididunt.',
    //     'description': 'Fugiat tempor consectetur laboris dolor ut adipisicing. Excepteur pariatur minim voluptate duis consectetur irure aute voluptate veniam deserunt elit quis Lorem duis.',
    //     'effectivityDate': '11/19/2014',
    //     'expiryDate': '08/07/2019',
    //     'status': 'terminated',
    //     'accomplishment': 25,
    //     'duration': 35
    // },
    // {
    //     'id': '15CH2998',
    //     'contractor': 'OPPORTECH',
    //     'contractName': 'Et id proident ex ad eu irure excepteur in.',
    //     'description': 'Velit est qui dolore reprehenderit duis do. Nostrud fugiat anim adipisicing cupidatat.',
    //     'effectivityDate': '11/12/2015',
    //     'expiryDate': '04/19/2020',
    //     'status': 'nys',
    //     'accomplishment': 58,
    //     'duration': 49
    // },
    // {
    //     'id': '15CH1510',
    //     'contractor': 'EMERGENT',
    //     'contractName': 'Consectetur cillum eiusmod deserunt commodo mollit cupidatat ipsum do.',
    //     'description': 'Dolor ullamco fugiat aliquip nulla voluptate quis esse. Mollit reprehenderit laborum commodo veniam exercitation qui aute sit eiusmod tempor minim nulla duis.',
    //     'effectivityDate': '06/06/2015',
    //     'expiryDate': '11/24/2020',
    //     'status': 'completed',
    //     'accomplishment': 77,
    //     'duration': 73
    // },
    // {
    //     'id': '15CH5273',
    //     'contractor': 'PHUEL',
    //     'contractName': 'Eiusmod et deserunt est Lorem pariatur ex deserunt.',
    //     'description': 'Mollit ut laboris dolor veniam incididunt magna Lorem esse ad. Nulla enim eiusmod dolore nulla adipisicing voluptate mollit magna labore laboris.',
    //     'effectivityDate': '03/29/2015',
    //     'expiryDate': '03/26/2019',
    //     'status': 'accepted',
    //     'accomplishment': 63,
    //     'duration': 51
    // },
    // {
    //     'id': '15CH3639',
    //     'contractor': 'LOTRON',
    //     'contractName': 'Exercitation voluptate culpa nostrud anim occaecat enim laboris pariatur est adipisicing dolor ex aliquip do.',
    //     'description': 'Veniam voluptate nostrud reprehenderit veniam sint magna magna proident veniam. Ullamco sit velit nisi non est veniam qui ex anim occaecat qui.',
    //     'effectivityDate': '01/28/2015',
    //     'expiryDate': '01/11/2020',
    //     'status': 'ongoing',
    //     'accomplishment': 75,
    //     'duration': 70
    // },
    // {
    //     'id': '15CH7928',
    //     'contractor': 'ZYTRAX',
    //     'contractName': 'Nostrud velit voluptate deserunt dolor incididunt incididunt fugiat nostrud minim voluptate consectetur sit.',
    //     'description': 'Laborum minim irure voluptate duis aliquip laboris nostrud ullamco Lorem commodo. Eiusmod officia et ut esse amet mollit duis non ut eiusmod mollit.',
    //     'effectivityDate': '06/20/2015',
    //     'expiryDate': '08/15/2020',
    //     'status': 'completed',
    //     'accomplishment': 15,
    //     'duration': 71
    // },
    // {
    //     'id': '15CH6836',
    //     'contractor': 'NURALI',
    //     'contractName': 'Ad veniam dolor deserunt amet laboris ullamco aliquip.',
    //     'description': 'Mollit exercitation nostrud nulla enim anim eu exercitation dolore. Pariatur dolore labore proident occaecat adipisicing.',
    //     'effectivityDate': '05/18/2015',
    //     'expiryDate': '09/15/2020',
    //     'status': 'completed',
    //     'accomplishment': 21,
    //     'duration': 23
    // },
    // {
    //     'id': '15CH9828',
    //     'contractor': 'NUTRALAB',
    //     'contractName': 'Aliqua commodo id laboris deserunt do.',
    //     'description': 'Veniam consectetur ad laboris nisi eiusmod sint consequat nostrud ex occaecat consequat cillum officia. Ullamco pariatur consequat proident anim cupidatat veniam velit velit.',
    //     'effectivityDate': '12/12/2015',
    //     'expiryDate': '03/27/2020',
    //     'status': 'completed',
    //     'accomplishment': 20,
    //     'duration': 96
    // },
    // {
    //     'id': '15CH3269',
    //     'contractor': 'FILODYNE',
    //     'contractName': 'Sunt enim ea deserunt aliquip voluptate occaecat sunt mollit veniam exercitation est irure et.',
    //     'description': 'In laborum cupidatat deserunt id veniam sit consectetur. Adipisicing mollit voluptate id qui incididunt amet amet irure consequat aliqua.',
    //     'effectivityDate': '11/13/2015',
    //     'expiryDate': '05/28/2018',
    //     'status': 'accepted',
    //     'accomplishment': 51,
    //     'duration': 45
    // },
    // {
    //     'id': '15CH7759',
    //     'contractor': 'CUJO',
    //     'contractName': 'Officia nisi tempor ullamco non occaecat laborum culpa do magna excepteur mollit reprehenderit nostrud.',
    //     'description': 'Lorem reprehenderit ad cupidatat proident amet anim irure. Tempor ad mollit nulla officia ipsum.',
    //     'effectivityDate': '08/24/2015',
    //     'expiryDate': '07/19/2018',
    //     'status': 'terminated',
    //     'accomplishment': 76,
    //     'duration': 9
    // },
    // {
    //     'id': '15CH3064',
    //     'contractor': 'MARTGO',
    //     'contractName': 'Irure est in culpa amet velit.',
    //     'description': 'Cupidatat irure esse commodo laborum nostrud aliqua anim minim irure. Sit elit quis officia in amet dolore non labore nostrud cupidatat ea.',
    //     'effectivityDate': '08/08/2015',
    //     'expiryDate': '06/27/2018',
    //     'status': 'accepted',
    //     'accomplishment': 18,
    //     'duration': 41
    // },
    // {
    //     'id': '15CH7079',
    //     'contractor': 'SNACKTION',
    //     'contractName': 'In magna in esse proident exercitation cupidatat esse elit ea minim do ullamco laborum mollit.',
    //     'description': 'Pariatur officia pariatur do mollit ipsum Lorem laborum. Laboris occaecat irure nostrud aute voluptate velit ipsum anim culpa aute veniam nostrud adipisicing cupidatat.',
    //     'effectivityDate': '06/19/2014',
    //     'expiryDate': '10/16/2019',
    //     'status': 'nys',
    //     'accomplishment': 12,
    //     'duration': 42
    // },
    // {
    //     'id': '15CH6694',
    //     'contractor': 'ZENSUS',
    //     'contractName': 'Qui laboris adipisicing excepteur laboris enim sit id ullamco pariatur adipisicing.',
    //     'description': 'Officia ut commodo tempor laboris aliqua et aute commodo aliquip consectetur. Duis consequat occaecat occaecat occaecat id.',
    //     'effectivityDate': '02/03/2015',
    //     'expiryDate': '07/07/2020',
    //     'status': 'nys',
    //     'accomplishment': 82,
    //     'duration': 73
    // },
    // {
    //     'id': '15CH6954',
    //     'contractor': 'INTERLOO',
    //     'contractName': 'Duis ea laboris ut incididunt deserunt consequat culpa velit voluptate tempor.',
    //     'description': 'Occaecat commodo enim minim minim deserunt consectetur sit deserunt incididunt. Anim nisi consectetur anim magna deserunt ut deserunt adipisicing.',
    //     'effectivityDate': '06/01/2015',
    //     'expiryDate': '03/17/2021',
    //     'status': 'completed',
    //     'accomplishment': 94,
    //     'duration': 15
    // },
    // {
    //     'id': '15CH9434',
    //     'contractor': 'SPACEWAX',
    //     'contractName': 'Sit culpa enim pariatur culpa aliquip occaecat exercitation cillum ipsum aliquip in minim.',
    //     'description': 'Pariatur do ex tempor incididunt dolore ut et consequat. Nisi incididunt Lorem id minim.',
    //     'effectivityDate': '01/15/2014',
    //     'expiryDate': '12/19/2020',
    //     'status': 'ongoing',
    //     'accomplishment': 55,
    //     'duration': 32
    // },
    // {
    //     'id': '15CH4681',
    //     'contractor': 'SUREMAX',
    //     'contractName': 'Tempor id duis laborum velit non ad dolore aliquip velit eiusmod nulla.',
    //     'description': 'Voluptate laborum enim aliquip velit. Cupidatat ullamco nostrud nisi anim elit dolor mollit nostrud nisi non.',
    //     'effectivityDate': '02/06/2014',
    //     'expiryDate': '12/22/2017',
    //     'status': 'terminated',
    //     'accomplishment': 46,
    //     'duration': 18
    // },
    // {
    //     'id': '15CH8207',
    //     'contractor': 'FLOTONIC',
    //     'contractName': 'Commodo adipisicing reprehenderit dolor consequat aliqua dolore nostrud nostrud qui incididunt eiusmod tempor.',
    //     'description': 'Esse sunt fugiat ut eu voluptate proident. Nostrud exercitation et dolore mollit irure occaecat minim irure dolore.',
    //     'effectivityDate': '02/09/2014',
    //     'expiryDate': '04/24/2016',
    //     'status': 'completed',
    //     'accomplishment': 75,
    //     'duration': 54
    // },
    // {
    //     'id': '15CH5798',
    //     'contractor': 'BUZZNESS',
    //     'contractName': 'Id non consectetur fugiat sint velit sunt irure cillum laborum.',
    //     'description': 'Sint ea deserunt eu aute ipsum consequat cillum ullamco amet non aliqua minim esse laboris. Mollit Lorem sunt ad consectetur exercitation culpa proident labore deserunt ipsum exercitation exercitation aliquip.',
    //     'effectivityDate': '09/22/2014',
    //     'expiryDate': '08/01/2016',
    //     'status': 'terminated',
    //     'accomplishment': 62,
    //     'duration': 16
    // },
    // {
    //     'id': '15CH1318',
    //     'contractor': 'CENTICE',
    //     'contractName': 'Pariatur dolor mollit non aliquip velit ipsum velit cillum nisi id veniam aute.',
    //     'description': 'Est ex nostrud labore ad dolore aliquip fugiat id officia est incididunt excepteur. Ullamco sint commodo proident consequat est quis.',
    //     'effectivityDate': '11/25/2014',
    //     'expiryDate': '12/24/2017',
    //     'status': 'completed',
    //     'accomplishment': 56,
    //     'duration': 63
    // },
    // {
    //     'id': '15CH9988',
    //     'contractor': 'EXOSIS',
    //     'contractName': 'Reprehenderit enim labore deserunt nisi est fugiat laboris laboris incididunt.',
    //     'description': 'Officia aliqua sunt veniam labore reprehenderit excepteur exercitation eiusmod minim ut cupidatat. Cillum cillum non ipsum quis est ad eu nostrud elit in nisi nisi elit culpa.',
    //     'effectivityDate': '01/25/2015',
    //     'expiryDate': '07/04/2018',
    //     'status': 'accepted',
    //     'accomplishment': 88,
    //     'duration': 47
    // },
    // {
    //     'id': '15CH6008',
    //     'contractor': 'QUILTIGEN',
    //     'contractName': 'Tempor ipsum elit occaecat laboris veniam dolore ut amet culpa aliquip consequat tempor magna est.',
    //     'description': 'Dolor mollit laborum laborum deserunt proident. Est aliquip excepteur enim officia nostrud.',
    //     'effectivityDate': '05/01/2015',
    //     'expiryDate': '05/17/2018',
    //     'status': 'accepted',
    //     'accomplishment': 48,
    //     'duration': 40
    // },
    // {
    //     'id': '15CH6318',
    //     'contractor': 'BUZZOPIA',
    //     'contractName': 'Adipisicing duis aliqua ullamco non dolore id.',
    //     'description': 'Elit non dolor ipsum reprehenderit laboris. Est dolore commodo magna duis enim velit.',
    //     'effectivityDate': '05/28/2015',
    //     'expiryDate': '05/27/2017',
    //     'status': 'completed',
    //     'accomplishment': 100,
    //     'duration': 18
    // },
    // {
    //     'id': '15CH5976',
    //     'contractor': 'MANTRIX',
    //     'contractName': 'Nulla est laboris esse deserunt.',
    //     'description': 'Incididunt tempor nisi mollit occaecat irure esse. Nulla ea anim ex exercitation eiusmod laborum id adipisicing.',
    //     'effectivityDate': '12/22/2014',
    //     'expiryDate': '06/11/2017',
    //     'status': 'nys',
    //     'accomplishment': 39,
    //     'duration': 46
    // },
    // {
    //     'id': '15CH1161',
    //     'contractor': 'ZYTRAC',
    //     'contractName': 'Eu officia occaecat id aliquip ut aliquip reprehenderit eu esse irure ea laboris adipisicing.',
    //     'description': 'Elit reprehenderit aliquip duis non irure eiusmod velit in elit duis. Ipsum culpa veniam ut commodo quis tempor officia.',
    //     'effectivityDate': '04/21/2014',
    //     'expiryDate': '03/25/2018',
    //     'status': 'completed',
    //     'accomplishment': 5,
    //     'duration': 85
    // },
    // {
    //     'id': '15CH7048',
    //     'contractor': 'GEEKOL',
    //     'contractName': 'Et qui anim eu in dolore ad Lorem consectetur.',
    //     'description': 'Exercitation aliqua aute enim sit laborum nisi nisi duis. Occaecat ex est amet sint non veniam reprehenderit elit laboris eiusmod fugiat commodo.',
    //     'effectivityDate': '09/14/2015',
    //     'expiryDate': '05/16/2018',
    //     'status': 'terminated',
    //     'accomplishment': 84,
    //     'duration': 72
    // },
    // {
    //     'id': '15CH7032',
    //     'contractor': 'PYRAMAX',
    //     'contractName': 'Sunt ex adipisicing tempor irure ullamco aliqua ex nisi.',
    //     'description': 'Deserunt cupidatat quis enim voluptate amet aliquip occaecat elit cupidatat ullamco non exercitation. Anim incididunt non aute adipisicing quis id.',
    //     'effectivityDate': '02/25/2015',
    //     'expiryDate': '06/04/2020',
    //     'status': 'ongoing',
    //     'accomplishment': 78,
    //     'duration': 9
    // },
    // {
    //     'id': '15CH3579',
    //     'contractor': 'ISOLOGIA',
    //     'contractName': 'Pariatur est laboris cillum et esse qui excepteur aliqua.',
    //     'description': 'Exercitation sit enim nostrud tempor. Sit Lorem do sunt et consectetur fugiat proident aliquip tempor dolor tempor ad.',
    //     'effectivityDate': '01/27/2015',
    //     'expiryDate': '10/23/2020',
    //     'status': 'ongoing',
    //     'accomplishment': 61,
    //     'duration': 33
    // },
    // {
    //     'id': '15CH8420',
    //     'contractor': 'PANZENT',
    //     'contractName': 'Quis eu tempor enim esse voluptate ipsum in enim id mollit veniam labore ipsum.',
    //     'description': 'Dolor enim adipisicing excepteur consectetur est exercitation consequat reprehenderit exercitation culpa et officia. Occaecat aliquip consectetur magna ut proident minim occaecat enim.',
    //     'effectivityDate': '01/11/2015',
    //     'expiryDate': '01/05/2016',
    //     'status': 'terminated',
    //     'accomplishment': 77,
    //     'duration': 78
    // },
    // {
    //     'id': '15CH5105',
    //     'contractor': 'QIMONK',
    //     'contractName': 'Ex mollit id non voluptate eiusmod est proident aute nisi fugiat non.',
    //     'description': 'Dolor commodo aliquip laborum pariatur anim enim nulla ex qui id irure elit. Cupidatat do irure mollit excepteur ex irure cupidatat elit voluptate consectetur.',
    //     'effectivityDate': '03/22/2014',
    //     'expiryDate': '10/13/2019',
    //     'status': 'completed',
    //     'accomplishment': 33,
    //     'duration': 25
    // },
    // {
    //     'id': '15CH2265',
    //     'contractor': 'HYDROCOM',
    //     'contractName': 'Id irure irure in non sit adipisicing cillum deserunt consectetur minim.',
    //     'description': 'Et excepteur id Lorem nulla pariatur nulla esse irure voluptate commodo eu. Nostrud culpa id sit aute sunt officia cillum in culpa.',
    //     'effectivityDate': '10/09/2015',
    //     'expiryDate': '01/04/2016',
    //     'status': 'ongoing',
    //     'accomplishment': 85,
    //     'duration': 46
    // },
    // {
    //     'id': '15CH2088',
    //     'contractor': 'EXOPLODE',
    //     'contractName': 'Dolor esse ullamco ea minim officia enim excepteur aliquip irure ipsum ex incididunt incididunt.',
    //     'description': 'Commodo nulla irure irure incididunt occaecat dolore irure ullamco sit esse sint aliqua exercitation dolore. Labore aliqua sint reprehenderit cupidatat dolor consequat ea sint commodo irure ipsum.',
    //     'effectivityDate': '08/07/2015',
    //     'expiryDate': '10/02/2019',
    //     'status': 'completed',
    //     'accomplishment': 82,
    //     'duration': 47
    // },
    // {
    //     'id': '15CH7747',
    //     'contractor': 'GRONK',
    //     'contractName': 'Laboris cupidatat labore laborum sit in consectetur dolore mollit ut sit est.',
    //     'description': 'Consequat Lorem amet laboris esse qui do est tempor dolore. Aliqua voluptate eu consequat aliqua.',
    //     'effectivityDate': '07/13/2014',
    //     'expiryDate': '01/07/2020',
    //     'status': 'accepted',
    //     'accomplishment': 22,
    //     'duration': 12
    // },
    // {
    //     'id': '15CH9168',
    //     'contractor': 'SONGLINES',
    //     'contractName': 'Do dolore laborum minim incididunt sunt est.',
    //     'description': 'Minim ad aliqua esse nulla velit aute cillum do pariatur aute dolor commodo reprehenderit. Fugiat dolore elit id consectetur fugiat sit ea dolor commodo incididunt cillum ex laborum dolore.',
    //     'effectivityDate': '06/24/2015',
    //     'expiryDate': '05/12/2020',
    //     'status': 'terminated',
    //     'accomplishment': 92,
    //     'duration': 28
    // },
    // {
    //     'id': '15CH3396',
    //     'contractor': 'STEELTAB',
    //     'contractName': 'Ipsum adipisicing velit nulla duis ex occaecat.',
    //     'description': 'Ex excepteur voluptate eu commodo. Veniam amet eu nisi labore adipisicing magna adipisicing ea nisi nisi exercitation.',
    //     'effectivityDate': '03/20/2015',
    //     'expiryDate': '01/02/2017',
    //     'status': 'terminated',
    //     'accomplishment': 95,
    //     'duration': 5
    // },
    // {
    //     'id': '15CH1277',
    //     'contractor': 'PARLEYNET',
    //     'contractName': 'Officia officia esse ullamco quis.',
    //     'description': 'Tempor officia in cillum id. Fugiat culpa ad fugiat laboris amet quis ullamco.',
    //     'effectivityDate': '10/30/2015',
    //     'expiryDate': '09/01/2020',
    //     'status': 'nys',
    //     'accomplishment': 100,
    //     'duration': 75
    // },
    // {
    //     'id': '15CH8024',
    //     'contractor': 'COMFIRM',
    //     'contractName': 'Amet non enim excepteur ad consectetur officia magna amet nulla.',
    //     'description': 'Non magna Lorem tempor fugiat reprehenderit dolore adipisicing fugiat dolore in. Lorem dolor magna occaecat labore.',
    //     'effectivityDate': '09/03/2014',
    //     'expiryDate': '10/12/2019',
    //     'status': 'completed',
    //     'accomplishment': 65,
    //     'duration': 3
    // },
    // {
    //     'id': '15CH4366',
    //     'contractor': 'KLUGGER',
    //     'contractName': 'Deserunt ipsum consequat qui labore excepteur enim quis.',
    //     'description': 'Minim qui ex eu tempor dolor. Do ipsum nisi esse sit reprehenderit.',
    //     'effectivityDate': '03/04/2015',
    //     'expiryDate': '08/28/2019',
    //     'status': 'accepted',
    //     'accomplishment': 70,
    //     'duration': 100
    // },
    // {
    //     'id': '15CH3215',
    //     'contractor': 'XELEGYL',
    //     'contractName': 'Consectetur cupidatat sit eiusmod sunt ipsum ullamco reprehenderit deserunt est minim.',
    //     'description': 'Proident exercitation laboris reprehenderit adipisicing. Aute fugiat id ex occaecat enim exercitation Lorem et ex nostrud nostrud labore nostrud labore.',
    //     'effectivityDate': '10/15/2015',
    //     'expiryDate': '08/03/2020',
    //     'status': 'accepted',
    //     'accomplishment': 24,
    //     'duration': 32
    // },
    // {
    //     'id': '15CH1581',
    //     'contractor': 'DUFLEX',
    //     'contractName': 'Fugiat do elit fugiat mollit amet ea nulla.',
    //     'description': 'Amet ullamco consequat dolor ad irure sint anim sunt irure. Qui voluptate ullamco qui dolor.',
    //     'effectivityDate': '11/27/2015',
    //     'expiryDate': '05/29/2016',
    //     'status': 'completed',
    //     'accomplishment': 58,
    //     'duration': 13
    // },
    // {
    //     'id': '15CH4315',
    //     'contractor': 'EXOSPACE',
    //     'contractName': 'Ullamco fugiat eu anim consectetur.',
    //     'description': 'Fugiat in anim reprehenderit cillum labore. Velit cupidatat esse culpa eu dolore quis reprehenderit aliquip.',
    //     'effectivityDate': '01/27/2014',
    //     'expiryDate': '10/07/2017',
    //     'status': 'accepted',
    //     'accomplishment': 29,
    //     'duration': 9
    // },
    // {
    //     'id': '15CH8491',
    //     'contractor': 'DOGNOSIS',
    //     'contractName': 'Aute reprehenderit cupidatat ea excepteur exercitation pariatur dolore ea.',
    //     'description': 'Sint nulla deserunt deserunt voluptate anim consectetur. Minim cillum ipsum ex consequat est dolor qui dolor Lorem nisi eiusmod irure esse sint.',
    //     'effectivityDate': '02/06/2015',
    //     'expiryDate': '04/12/2017',
    //     'status': 'terminated',
    //     'accomplishment': 82,
    //     'duration': 42
    // },
    // {
    //     'id': '15CH7715',
    //     'contractor': 'BEADZZA',
    //     'contractName': 'Sunt consectetur minim ad deserunt tempor eiusmod aute ipsum.',
    //     'description': 'Magna dolor in consequat aute pariatur cupidatat. Commodo qui est Lorem aute irure id anim ea proident elit magna anim ut.',
    //     'effectivityDate': '11/12/2014',
    //     'expiryDate': '02/23/2017',
    //     'status': 'accepted',
    //     'accomplishment': 2,
    //     'duration': 79
    // },
    // {
    //     'id': '15CH6730',
    //     'contractor': 'AQUASSEUR',
    //     'contractName': 'Consequat enim ut mollit culpa consequat magna consectetur do fugiat nisi excepteur elit enim veniam.',
    //     'description': 'Irure eu duis eu eu in duis sunt. Labore aliquip reprehenderit culpa mollit velit.',
    //     'effectivityDate': '04/10/2015',
    //     'expiryDate': '11/14/2017',
    //     'status': 'terminated',
    //     'accomplishment': 35,
    //     'duration': 15
    // }
];
